export const ON_ADD_COUNTER = 'ON_ADD_COUNTER';
export const QUESTION_ANSWER_LIST = 'QUESTION_ANSWER_LIST';
export const QUESTION_ANSWER_LIST_M = 'QUESTION_ANSWER_LIST_M';
export const QUESTION_ANSWER_EDIT = 'QUESTION_ANSWER_EDIT';